services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
  wordpress:
    build: requirements/wordpress/
    container_name: wordpress-php
  mariadb:
    build: requirements/mariadb
    container name: mariadb