services:

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception
    

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
    restart: always
    networks:
      - inception
    environment:
      MARIADB_HOST: "${MARIADB_HOST}"
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    secrets:
      - mdb_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
    restart: always
    networks:
      - inception
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
    secrets:
      - mdb_password
      - mdb_root_password
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/triinueesmaa/data/mariadb_data
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/triinueesmaa/data/wordpress_data

networks:
  inception:
    driver: bridge

secrets:
  mdb_root_password:
    file: ./secrets/mdb_root_password.txt
  mdb_password:
    file: ./secrets/mdb_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt
